name: Node.js CI

on:
  push:
    branches: [ "main" ]    # runs on push to main
  pull_request:
    branches: [ "main" ]    # runs on PRs to main

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [18.x, 20.x]  # test multiple versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

    #   - name: Run tests
    #     run: npm test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Vercel Action
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: BjtGbvercLdtBk9ltDCsdske
          vercel-org-id: babloos-projects-5cd6b724
          vercel-project-id: prj_6pRZeRibu6rwbW5a6lXET2HaVDsC
          working-directory: ./
